
version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb-10turnerov2
    environment:
      MYSQL_ROOT_PASSWORD: Tangalanga11!
      MYSQL_DATABASE: vaadin_db
      MYSQL_USER: vaadin_user
      MYSQL_PASSWORD: tangalanga
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - vaadin_network

networks:
  vaadin_network:
    driver: bridge

